---
title: "Untitled"
date: "03/04/2022"
output: html_document
---

```{r setup, include=FALSE}
library(magrittr)
library(rvest)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
url <- "https://docs.api.wanikani.com/20170710/"
url <- "Introduction – WaniKani API Reference.html"
```


```{r}
data_html <- read_html(url)
```

```{r}

items <- data_html %>%
  html_nodes(
    xpath = "//*[@id='resources']/following-sibling::h1/following-sibling::h2[1]/@id"
    # xpath = "//*[@id='resources']/following-sibling::h1/following-sibling::table[1]"
    ) %>% html_text()
items
# %>%
# 
#     html_table()

 
```

```{r}
for (ii in 1:length(items)) {
  data_html %>%
    html_nodes(xpath = sprintf(
      "//*[@id='%s']/following-sibling::h2[1]/
        preceding-sibling::*[(self::table or self::h3 or self::h4 or self::h5 or self::h6) and
          preceding-sibling::*[@id='%s']
        ]", items[ii], items[ii])) %>%
    print()
}
```


```{r}
attributes <- NULL

for (ii in 1:length(items)) {
  parts <- data_html %>%
    html_nodes(xpath = sprintf(
      "//*[@id='%s']/following-sibling::h2[1]/
        preceding-sibling::table[preceding-sibling::*[@id='%s']]/
        preceding-sibling::*[self::h2 or self::h3 or self::h4 or self::h5][1]/
        preceding-sibling::*[1]/
        following-sibling::*[self::table or self::h2 or self::h3 or self::h4 or self::h5][position() <= 2]
      ", items[ii], items[ii]))
  
  for (jj in (1:(length(parts) / 2)) * 2 - 1) {
    t <- parts[jj + 1] %>% 
      html_table %>% 
      pluck(1)
    
    if (ncol(t) == 3) {
      names(t) <- c("Name", "Type", "Description")
      attributes %<>% 
        bind_rows(
          t %>%
            mutate(Class = items[ii], 
                   SubClass = parts[jj] %>% html_attr("id"),
                   Level = parts[jj] %>% html_name)
          )
    }
  }
}

attributes %<>%
  relocate(Class, SubClass, Level) %>%
  glimpse()
```

```{r}
attributes %>% write.csv2("Attributes.csv")

```

```{r}
classes <- attributes %>% select(SubClass) %>% distinct() %>% pull()
classes
```


